operatingSystem:
  windows: true

deployInfra:
  enabled: true
  storageAccount: true
  aiSearchService: true
  azureSpeechService: true
  containerRegistry: false
  appServicePremiumPlan: false
  appServiceBasicPlan: false
  eventHubService: true
  azureOpenAIService: true

envCreation:
  enabled: true

midentityCreation:
  enabled: true

buildAndPushImagesToACR:
  enabled: false
  buildMainApp: false
  buildIngestionConsumer: false

deployAppService:
  enabled: false

deployContainerApps:
  enabled: false